# Generated by Django 4.2.5 on 2023-09-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_duration_months_subscriptionplan_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='subscriptionticket',
            name='duration_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
