# Generated by Django 4.2.5 on 2023-09-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_subscriptionplan_duration_days_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionTicket',
            new_name='Subscription',
        ),
    ]
