# Generated by Django 4.2.5 on 2023-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_subscriptionticket_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='account_type',
            field=models.CharField(choices=[('NURSERY & PRIMARY SCHOOL', 'Nursery & Primary School'), ('JUNIOR & SENIOR SECONDARY SCHOOL', 'Junior & Senior Secondary School'), ('JUNIOR SECONDARY SCHOOL', 'Junior Secondary School'), ('SENIOR SECONDARY SCHOOL', 'Senior Secondary School')], max_length=100, null=True),
        ),
    ]
