# Generated by Django 4.2.5 on 2023-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_businessaccount_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaccount',
            old_name='activated_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
