# Generated by Django 4.2.5 on 2023-10-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_activated_date_businessaccount_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='lga',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
